// The parts of the KreditCheckout contract the browser and the server share.
// The contract itself lives in contracts/src/KreditCheckout.sol.

export const CHECKOUT_ABI = [
  {
    type: "function",
    name: "buyWithUsdg",
    stateMutability: "nonpayable",
    inputs: [{ name: "credits", type: "uint256" }],
    outputs: [{ name: "amount", type: "uint256" }],
  },
  {
    type: "function",
    name: "buyWithEth",
    stateMutability: "payable",
    inputs: [
      { name: "minCredits", type: "uint256" },
      { name: "deadline", type: "uint256" },
    ],
    outputs: [
      { name: "amount", type: "uint256" },
      { name: "credits", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "creditsFor",
    stateMutability: "view",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "costOf",
    stateMutability: "view",
    inputs: [{ name: "credits", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  { type: "function", name: "usdg", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "treasury", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "owner", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "weth", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "router", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "poolFee", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint24" }] },
  { type: "function", name: "usdgPerCredit", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "maxCreditsPerBuy", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "paused", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "purchased", stateMutability: "view", inputs: [{ name: "", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "totalPurchased", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "setPrice", stateMutability: "nonpayable", inputs: [{ name: "usdgPerCredit_", type: "uint256" }], outputs: [] },
  { type: "function", name: "setTreasury", stateMutability: "nonpayable", inputs: [{ name: "treasury_", type: "address" }], outputs: [] },
  { type: "function", name: "setMaxCreditsPerBuy", stateMutability: "nonpayable", inputs: [{ name: "maxCreditsPerBuy_", type: "uint256" }], outputs: [] },
  { type: "function", name: "setPaused", stateMutability: "nonpayable", inputs: [{ name: "paused_", type: "bool" }], outputs: [] },
  {
    type: "event",
    name: "Purchased",
    inputs: [
      { name: "buyer", type: "address", indexed: true },
      { name: "token", type: "address", indexed: true },
      { name: "ethIn", type: "uint256", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "credits", type: "uint256", indexed: false },
    ],
  },
  { type: "error", name: "NotOwner", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "ZeroPrice", inputs: [] },
  { type: "error", name: "BadFee", inputs: [] },
  { type: "error", name: "Paused", inputs: [] },
  { type: "error", name: "NothingSent", inputs: [] },
  { type: "error", name: "NothingBought", inputs: [] },
  { type: "error", name: "TooMuch", inputs: [{ name: "credits", type: "uint256" }, { name: "max", type: "uint256" }] },
  { type: "error", name: "Expired", inputs: [] },
  { type: "error", name: "Reentered", inputs: [] },
  { type: "error", name: "TransferFailed", inputs: [] },
] as const;
